/**
 * How many still count at each of the ending's levy stops (world.ts
 * `VEIL_STOPS`), at a 10% stake: mean effective participants of 8 finished
 * rooms each, under the guided outcome protocol (N = 100, 200,000 trades,
 * levy once a round, tail averaged after burn-in). GENERATED by
 * scripts/veil-counts.ts — do not edit by hand.
 */
export const VEIL_COUNTS: readonly number[] = [7.10, 11.76, 22.53, 42.03, 65.87, 82.98, 93.90, 98.40, 100.00];
