/**
 * The tightest known ways to pile n equal coins inside a circle, n = 1…16,
 * written to `src/lib/widgets/stage/scenes/pair/packings.ts`.
 *
 *   npx vite-node scripts/coin-packings.ts
 *
 * Run once; the output is committed data. Shrink-and-relax: for a container
 * radius R, push overlapping coins apart and pull stray ones inside until
 * nothing moves; bisect on R; keep the best of many random starts. For n ≤ 16
 * that lands within a hair of the published optima (Packomania), which the
 * test checks.
 */
import { writeFileSync } from 'node:fs';

type P = { x: number; y: number };

const MAX_N = 16;
const STARTS = 90;

function rng(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/** Relax unit coins into a container of radius R; returns the worst remaining violation. */
function relax(points: P[], R: number, rounds: number): number {
  const inner = R - 1;
  let worst = 0;
  for (let round = 0; round < rounds; round++) {
    worst = 0;
    for (let i = 0; i < points.length; i++) {
      for (let j = i + 1; j < points.length; j++) {
        const dx = points[j].x - points[i].x;
        const dy = points[j].y - points[i].y;
        const d = Math.hypot(dx, dy) || 1e-9;
        if (d < 2) {
          const push = (2 - d) / 2;
          worst = Math.max(worst, 2 - d);
          points[i].x -= (dx / d) * push;
          points[i].y -= (dy / d) * push;
          points[j].x += (dx / d) * push;
          points[j].y += (dy / d) * push;
        }
      }
    }
    for (const p of points) {
      const d = Math.hypot(p.x, p.y);
      if (d > inner) {
        worst = Math.max(worst, d - inner);
        const k = inner / d;
        p.x *= k;
        p.y *= k;
      }
    }
    if (worst < 1e-10) break;
  }
  return worst;
}

function pack(n: number): { R: number; points: P[] } {
  if (n === 1) return { R: 1, points: [{ x: 0, y: 0 }] };
  let best: { R: number; points: P[] } | null = null;
  for (let start = 0; start < (n === 9 ? STARTS * 8 : STARTS); start++) {
    const rand = rng(n * 1000 + start);
    const high0 = Math.sqrt(n) * 1.6 + 1;
    let points = Array.from({ length: n }, () => {
      const a = rand() * Math.PI * 2;
      const r = Math.sqrt(rand()) * (high0 - 1);
      return { x: Math.cos(a) * r, y: Math.sin(a) * r };
    });
    let low = Math.sqrt(n / 0.91);
    let high = high0;
    relax(points, high, 4000);
    let feasible = points.map((p) => ({ ...p }));
    for (let step = 0; step < 34; step++) {
      const mid = (low + high) / 2;
      const trial = feasible.map((p) => ({ x: p.x * (mid - 1) / (high - 1), y: p.y * (mid - 1) / (high - 1) }));
      if (relax(trial, mid, 3000) < 1e-7) {
        high = mid;
        feasible = trial;
      } else {
        low = mid;
      }
    }
    points = feasible;
    if (!best || high < best.R) best = { R: high, points };
  }
  return best!;
}

/** Put one coin on the floor of the pile, so every count rests the same way up. */
function rest(points: P[]): P[] {
  const outer = Math.max(...points.map((p) => Math.hypot(p.x, p.y)));
  const floor = points
    .filter((p) => Math.hypot(p.x, p.y) > outer - 1e-3)
    .reduce((a, b) => (b.y > a.y ? b : a));
  const turn = Math.PI / 2 - Math.atan2(floor.y, floor.x);
  const c = Math.cos(turn);
  const s = Math.sin(turn);
  return points
    .map((p) => ({ x: p.x * c - p.y * s, y: p.x * s + p.y * c }))
    .map((p) => ({ x: Math.abs(p.x) < 1e-9 ? 0 : p.x, y: Math.abs(p.y) < 1e-9 ? 0 : p.y }));
}

const rows: string[] = [];
for (let n = 1; n <= MAX_N; n++) {
  const { R, points } = pack(n);
  const placed = rest(points);
  const coords = placed.map((p) => `[${p.x.toFixed(5)}, ${p.y.toFixed(5)}]`).join(', ');
  rows.push(`  { radius: ${R.toFixed(5)}, centres: [${coords}] },`);
  console.log(`n=${n} R=${R.toFixed(5)} density=${(n / (R * R)).toFixed(4)}`);
}

const out = `/**
 * The tightest known piles of n equal coins in a circle, n = 1…${MAX_N}, for coins
 * of radius 1. GENERATED by scripts/coin-packings.ts — do not edit by hand.
 * \`radius\` is the enclosing circle; \`centres\` are coin centres, one coin
 * resting at the bottom. Index 0 is n = 1.
 */
export interface Packing {
  readonly radius: number;
  readonly centres: readonly (readonly [number, number])[];
}

export const PACKINGS: readonly Packing[] = [
${rows.join('\n')}
];
`;
writeFileSync('src/lib/widgets/stage/scenes/pair/packings.ts', out);
