/**
 * The outcome map of Scene 24 — stake across, levy up, each square how many
 * still count — written to `src/lib/widgets/stage/scenes/pair/outcomeMap.ts`.
 *
 *   npx vite-node scripts/outcome-map.ts
 *
 * Run once; the output is committed data. Every square is the mean effective
 * participants of RUNS independent finished rooms under the guided outcome
 * protocol (N = 100, 200,000 trades, the levy once a round, the tail averaged
 * after burn-in) — the same protocol the old outcome-map widget filled in the
 * page, now measured once, seeded, and more runs per square.
 */
import { writeFileSync } from 'node:fs';
import { GUIDED_OUTCOME_PROTOCOL, runOutcome } from '../src/lib/research';

const STAKES = Array.from({ length: 10 }, (_, i) => 0.05 + i * 0.05);
const LEVIES = Array.from({ length: 15 }, (_, i) => i * 0.01);
const RUNS = 8;
const SEED = 20260926;

const started = Date.now();
const rows = LEVIES.map((levy, iy) =>
  STAKES.map((stake, ix) => {
    let sum = 0;
    for (let k = 0; k < RUNS; k++) {
      const seed = (SEED + (iy * STAKES.length + ix) * RUNS + k) >>> 0;
      sum += runOutcome({ ...GUIDED_OUTCOME_PROTOCOL, beta: stake, taxRate: levy, seed }).effectiveParticipants;
    }
    return sum / RUNS;
  }),
);
console.log(`measured ${LEVIES.length * STAKES.length * RUNS} rooms in ${((Date.now() - started) / 1000).toFixed(1)} s`);
for (let iy = LEVIES.length - 1; iy >= 0; iy--) console.log(rows[iy].map((v) => v.toFixed(0).padStart(4)).join(''));

const round = (x: number) => Number(x.toFixed(4));
const out = `/**
 * The outcome map of Scene 24: mean effective participants of ${RUNS} independent
 * finished rooms per square, stake across, levy per round up, under the guided
 * outcome protocol (N = ${GUIDED_OUTCOME_PROTOCOL.n}, ${GUIDED_OUTCOME_PROTOCOL.trades.toLocaleString('en')} trades, levy once a round,
 * tail averaged after burn-in). GENERATED by scripts/outcome-map.ts — do not
 * edit by hand. Finite-run measurements: neither a contour nor a fit drawn on
 * them is a phase boundary.
 */
export const MAP_STAKES: readonly number[] = [${STAKES.map(round).join(', ')}];
export const MAP_LEVIES: readonly number[] = [${LEVIES.map(round).join(', ')}];
export const MAP_RUNS = ${RUNS};
/** [levy][stake] */
export const MAP_PARTICIPANTS: readonly (readonly number[])[] = [
${rows.map((row) => `  [${row.map((v) => v.toFixed(2)).join(', ')}],`).join('\n')}
];
`;
writeFileSync('src/lib/widgets/stage/scenes/pair/outcomeMap.ts', out);
