/**
 * How many still count at each of the ending's levy stops, at the room's stake
 * (10%) — the colour a shared world wears — written to
 * `src/lib/widgets/stage/scenes/pair/veilCounts.ts`.
 *
 *   npx vite-node scripts/veil-counts.ts
 *
 * Run once; the output is committed data. Each stop is the mean effective
 * participants of RUNS independent finished rooms under the guided outcome
 * protocol, the same protocol as the outcome map (scripts/outcome-map.ts).
 */
import { writeFileSync } from 'node:fs';
import { GUIDED_OUTCOME_PROTOCOL, runOutcome } from '../src/lib/research';
import { VEIL_STOPS } from '../src/lib/widgets/stage/scenes/pair/world';

const STAKE = 0.1;
const RUNS = 8;
const SEED = 20261010;

const counts = VEIL_STOPS.map((levy, i) => {
  let sum = 0;
  for (let k = 0; k < RUNS; k++) sum += runOutcome({ ...GUIDED_OUTCOME_PROTOCOL, beta: STAKE, taxRate: levy, seed: (SEED + i * RUNS + k) >>> 0 }).effectiveParticipants;
  return sum / RUNS;
});
VEIL_STOPS.forEach((levy, i) => console.log(`${(levy * 100).toString().padStart(6)}%  ${counts[i].toFixed(1)}`));

const out = `/**
 * How many still count at each of the ending's levy stops (world.ts
 * \`VEIL_STOPS\`), at a 10% stake: mean effective participants of ${RUNS} finished
 * rooms each, under the guided outcome protocol (N = ${GUIDED_OUTCOME_PROTOCOL.n}, ${GUIDED_OUTCOME_PROTOCOL.trades.toLocaleString('en')} trades,
 * levy once a round, tail averaged after burn-in). GENERATED by
 * scripts/veil-counts.ts — do not edit by hand.
 */
export const VEIL_COUNTS: readonly number[] = [${counts.map((v) => v.toFixed(2)).join(', ')}];
`;
writeFileSync('src/lib/widgets/stage/scenes/pair/veilCounts.ts', out);
